### PR TITLE
Awesome books: with ES6

### PR DESCRIPTION
**Pull request by d4nQw3rty**
This project will restructure the Awesome books app code. The goal is to make it more organized by using modules. Also will use the ES6 syntax.

**General requirements:**
- Make sure there are no linter errors.
- Follow the correct git and GitHub workflows.
- Follow Microverse´s list of the [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).
- Follow Microverse's list of [best practices for JavaScript](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).
- Create an index.css file for your styles.
- Create the entry point for your JavaScript code called index.js
- Create the main index.html file. Link your index.js and index.css files there.
- Create a directory called modules.

**Re-create your Awesome books app following the rules**
- Use ES6 syntax.
- Divide your code into modules. Save each module in a separate file in the modules dir. Import modules in the index.js file. For this exercise - the more modules the better!
- Keep all functionalities of the app without errors.
- Refactor your methods and functions to arrow functions.
- Correctly use let and const.

**Display the current date below the navigation bar.**
- This requires the use of the library [Luxon](https://moment.github.io/luxon/#/install?id=es6)
- Import it as a module.

### CODE REVIEW

**Review by danmainah — APPROVED** [review]
Hi @d4nQw3rty , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by enniopo** [comment]
Hi @d4nQw3rty - please fix the linters error. 
The activity status on your dashboard has been updated so you can now request another code review request when you are ready. Thanks and sorry for the incoveniece.

**Comment by d4nQw3rty** [comment]
Hi Mr. Ennio; @enniopo  I want to start to apologize for all issues I cause by my
action trying to deploy the application after asking for a pull request. I
tried to undo the submission but it was too late. I understand that having
no linter is a mandatory requirement, I got the status approved then I fix
the linters and merge the project, and now a received this email. And I am
worried about what to do because my dashboard has the status completed, I
do not want to have unacceptable behavior and not report this issue, I will
accept any penalty.
Hope you have a great day, and awaiting your response.
Danys de Jesus ***@***.***' Linares  Moya.

**Comment by enniopo** [comment]
@d4nQw3rty it is all good now. No other action is needed.

**Pull request merged**
